---
# SafeLine WAF + VPS Ansible Playbook Configuration
# Production-ready configuration for SafeLine WAF deployment (Localhost optimized)

# ================================================================
# SYSTEM CONFIGURATION
# ================================================================

# Create swap file configuration
create_swap: false
swap_file_size: 2G
swap_file_path: /swapfile

# Timezone configuration
timezone: Europe/Moscow

# Enable log rotation
enable_log_rotation: true

# ================================================================
# BACKUP CONFIGURATION
# ================================================================

backup_enabled: false            # включить резервное копирование
backup_directory: /opt/backups   # директория для хранения бэкапов
backup_retention_days: 30        # число дней для хранения

# ================================================================
# SYSTEM PACKAGES
# ================================================================

system_packages:
  - curl
  - wget
  - git
  - htop
  - unzip
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# ================================================================
# SAFELINE WAF CONFIGURATION
# ================================================================

safeline_directory: /opt/safeline
safeline_admin_port: 9443
safeline_web_port: 80
safeline_https_port: 443

safeline_scripts:
  - name: safeline-password
    path: /usr/local/bin/safeline-password
  - name: safeline-ctl
    path: /usr/local/bin/safeline-ctl

# ================================================================
# ACCESS CONTROL CONFIGURATION (LOCALHOST OPTIMIZED)
# ================================================================

admin_allowed_ips:
  - 127.0.0.1/32       # Localhost IPv4
  - ::1/128            # Localhost IPv6
  - 192.168.1.0/24     # Локальная сеть (если нужен внешний доступ)
  # - YOUR_EXTERNAL_IP/32  # Ваш внешний IP (раскомментируйте если нужен внешний доступ)

ssh_allowed_ips: "{{ admin_allowed_ips }}"

# ================================================================
# DOCKER CONFIGURATION
# ================================================================

docker_edition: ce

docker_users:
  - "{{ ansible_user | default('root') }}"

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

# Use Docker Compose plugin instead of standalone binary
docker_compose_plugin: true

# ================================================================
# NGINX REVERSE PROXY CONFIGURATION (OPTIONAL)
# ================================================================

install_nginx: false

nginx_worker_processes: auto
nginx_worker_connections: 1024
nginx_client_max_body_size: 100M

nginx_geoip_enabled: false
nginx_blocked_countries:
  - CN  # China
  - RU  # Russia (пример - удалите если не нужно)

# ================================================================
# UFW FIREWALL CONFIGURATION
# ================================================================

ufw_enabled: true
ufw_logging: medium
ufw_default_input_policy: deny
ufw_default_output_policy: allow
ufw_default_forward_policy: deny

ufw_rules:
  - { rule: 'allow', port: '22', proto: 'tcp', comment: 'SSH access' }
  - { rule: 'allow', port: '80', proto: 'tcp', comment: 'HTTP access' }
  - { rule: 'allow', port: '443', proto: 'tcp', comment: 'HTTPS access' }
  - { rule: 'allow', port: '{{ safeline_admin_port }}', proto: 'tcp', from_ip: '127.0.0.1', comment: 'SafeLine admin panel localhost' }
  - { rule: 'allow', port: '{{ safeline_admin_port }}', proto: 'tcp', from_ip: '::1', comment: 'SafeLine admin panel localhost IPv6' }
  - { rule: 'allow', port: '9080', proto: 'tcp', from_ip: '127.0.0.1', comment: 'SafeLine internal' }
  - { rule: 'allow', from_ip: '172.16.0.0/12', comment: 'Docker networks' }
  - { rule: 'allow', from_ip: '192.168.0.0/16', comment: 'Local networks' }
  - { rule: 'allow', from_ip: '127.0.0.0/8', comment: 'Loopback interface' }

# ================================================================
# FAIL2BAN CONFIGURATION  
# ================================================================

fail2ban_enabled: true
fail2ban_bantime: '24h'
fail2ban_findtime: '10m'
fail2ban_maxretry: 3
fail2ban_ssh_maxretry: 5
fail2ban_ssh_bantime: '1h'
fail2ban_blocktype: 'reject'

fail2ban_ignoreip:
  - '127.0.0.1/8'      # Localhost IPv4
  - '::1'             # IPv6 localhost
  - '192.168.1.0/24'  # Local network

# ================================================================
# COMMON ROLE VARIABLES (LOCALHOST OPTIMIZED)
# ================================================================

target_user: "{{ ansible_user | default('root') }}"

additional_packages:
  - vim
  - tree
  - screen
  - net-tools
  - dnsutils

swap_size: "{{ swap_file_size | default('2G') }}"
swap_swappiness: 10

max_open_files: 65536
max_processes: 32768

# ================================================================
# LOCALHOST OPTIMIZATIONS (НОВЫЙ РАЗДЕЛ)
# ================================================================

localhost_mode: true
single_node_deployment: true
local_backup_path: "/home/{{ ansible_user | default('root') }}/safeline-backups"

# SAFE LINE ENVIRONMENT DEFAULTS
safeline_postgres_password: 'changeme'
# Только префикс сети без маски
safeline_subnet_prefix: '172.16.238'

safeline_image_prefix: "chaitin"
safeline_region: ""         # Пустая строка для международной версии
safeline_arch_suffix: ""    # Пустая строка для AMD64
safeline_release: ""        # Пустая строка для стабильной версии  
safeline_image_tag: "9.1.0"

container_timezone: '{{ timezone }}'
