---
# SafeLine WAF + VPS Ansible Playbook Configuration
# Production-ready configuration for SafeLine WAF deployment (Localhost optimized)

# ================================================================
# SYSTEM CONFIGURATION
# ================================================================

# Create swap file configuration
create_swap: true
swap_file_size: 2G
swap_file_path: /swapfile

# System packages to install
system_packages:
  - curl
  - wget
  - git
  - htop
  - unzip
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

# ================================================================
# SAFELINE WAF CONFIGURATION
# ================================================================

# SafeLine installation directory
safeline_directory: /opt/safeline

# SafeLine admin panel port (HTTPS)
safeline_admin_port: 9443

# SafeLine web panel port (HTTP redirect)
safeline_web_port: 80

# SafeLine management scripts
safeline_scripts:
  - name: safeline-password
    path: /usr/local/bin/safeline-password
  - name: safeline-ctl
    path: /usr/local/bin/safeline-ctl

# ================================================================
# ACCESS CONTROL CONFIGURATION (LOCALHOST OPTIMIZED)
# ================================================================

# Admin IP addresses allowed to access SafeLine panel
# ОПТИМИЗИРОВАНО ДЛЯ LOCALHOST: Доступ только с локальной машины
admin_allowed_ips:
  - 127.0.0.1/32       # Localhost IPv4
  - ::1/128             # Localhost IPv6  
  - 192.168.1.0/24     # Локальная сеть (если нужен внешний доступ)
  # - YOUR_EXTERNAL_IP/32  # Ваш внешний IP (раскомментируйте если нужен внешний доступ)

# SSH allowed IPs (для localhost не критично, но сохранено для совместимости)
ssh_allowed_ips: "{{ admin_allowed_ips }}"

# ================================================================
# DOCKER CONFIGURATION
# ================================================================

# Docker installation
docker_edition: ce
docker_users:
  - "{{ ansible_user }}"

# Docker Compose version
docker_compose_version: "2.24.0"

# ================================================================
# NGINX REVERSE PROXY CONFIGURATION (OPTIONAL)
# ================================================================

# Install Nginx reverse proxy with GeoIP filtering
install_nginx: false

# Nginx configuration (if enabled)
nginx_worker_processes: auto
nginx_worker_connections: 1024
nginx_client_max_body_size: 100M

# GeoIP configuration (if nginx enabled)
nginx_geoip_enabled: false
nginx_blocked_countries:
  - CN  # China
  - RU  # Russia (пример - удалите если не нужно)

# ================================================================
# UFW FIREWALL CONFIGURATION
# ================================================================

# Enable UFW firewall
ufw_enabled: true

# UFW logging level (off, low, medium, high, full)
ufw_logging: medium

# UFW default policies
ufw_default_input_policy: deny
ufw_default_output_policy: allow
ufw_default_forward_policy: deny

# UFW rules configuration
ufw_rules:
  # SSH access (для localhost можно отключить, но сохранено
