---
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
    update_cache: true
  become: true
  tags: nginx

- name: Ensure GeoIP module packages are present (опционально)
  apt:
    name: [libnginx-mod-http-geoip2, geoipupdate]
    state: present
  become: true
  when: geoip_enabled|default(false)
  tags: nginx

- name: Deploy global nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  become: true
  notify: reload nginx
  tags: nginx

- name: Deploy site config
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/safeline.conf
    mode: 0644
  become: true
  notify: reload nginx
  tags: nginx

- name: Enable site config
  file:
    src: /etc/nginx/sites-available/safeline.conf
    dest: /etc/nginx/sites-enabled/safeline.conf
    state: link
    force: true
  become: true
  notify: reload nginx
  tags: nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  notify: reload nginx
  tags: nginx

- name: Ensure Nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: true
  become: true
  tags: nginx
