---
# Handlers for firewall role

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    daemon_reload: yes
  listen: restart fail2ban

- name: reload ufw
  ufw:
    state: reloaded
  listen: reload ufw

- name: restart ufw
  systemd:
    name: ufw
    state: restarted
  listen: restart ufw
