---
# Firewall configuration with UFW and fail2ban

- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: [ufw, firewall]

- name: Reset UFW to defaults
  ufw:
    state: reset
  tags: [ufw, firewall]

- name: Enable UFW with default policies
  ufw:
    state: enabled
    policy: "{{ item.policy }}"
    direction: "{{ item.direction }}"
  loop:
    - { policy: 'deny', direction: 'incoming' }
    - { policy: 'allow', direction: 'outgoing' }
  tags: [ufw, firewall]

- name: Add dummy rule for fail2ban compatibility
  ufw:
    rule: allow
    from_ip: 127.0.0.1
    to_port: 1
    comment: "dummy-rule-for-fail2ban"
  tags: [ufw, firewall]

- name: Configure UFW basic rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default('tcp') }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ ufw_rules }}"
  when: ufw_rules is defined
  tags: [ufw, firewall]

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes
  when: fail2ban_enabled | default(true)
  tags: [fail2ban, firewall]

- name: Ensure fail2ban is stopped before configuration
  systemd:
    name: fail2ban
    state: stopped
  when: fail2ban_enabled | default(true)
  tags: [fail2ban, firewall]

- name: Create updated ufw.conf action for fail2ban
  template:
    src: ufw.conf.j2
    dest: /etc/fail2ban/action.d/ufw.conf
    backup: yes
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  when: fail2ban_enabled | default(true)
  tags: [fail2ban, firewall]

- name: Create fail2ban jail.local configuration
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    backup: yes
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  when: fail2ban_enabled | default(true)
  tags: [fail2ban, firewall]

- name: Start and enable fail2ban service
  systemd:
    name: fail2ban
    state: started
    enabled: yes
  when: fail2ban_enabled | default(true)
  tags: [fail2ban, firewall]

- name: Ждать запуска fail2ban
  command: systemctl is-active fail2ban
  register: fail2ban_status
  retries: 5
  delay: 2
  until: fail2ban_status.stdout == "active"
  when: fail2ban_enabled | default(true)
  tags:
    - fail2ban
    - firewall

